### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by FiskFan1999** [FiskFan1999/wvlist#1]
Here is my working prototype for which flags to use. Especially wondering if anyone has any recommendations for the defaults

- `-p` plaintext port, set to 0 if disabled (default 6060 or some arbitrary port)
- `-t` TLS port, set to 0 if disabled (default 0)*
- `-d` Debug mode, listen and serve TLS muxer on plaintext (this allows the operator console to be used in plaintext while testing, should not be run in prod) (default false)
- `-k` Key, path to fullchain.pem file (/etc/letsencrypt/live/wvlist.net/fullchain.pem) (default "")
- `-s` Secret, path to private key file (same) (default "")
- `-c` Config, path to config file (default ./config.json)

\* consider that `http.ListenAndServeTLS` would panic if it is run with invalid paths (which is also the default).

**Comment by FiskFan1999** [comment]
I'm open to suggestions to change these, but once we reach v1.0.0 release candidates we should probably lock these in, unless we add more params later.

I'm also considering wether we should have one param to say what to do (`./wvlist.exe run`, `./wvlist.exe mkcerts`, `./wvlist.exe passwd`, etc)

**Comment by tacerus** [comment]
> I'm also considering wether we should have one param to say what to do (`./wvlist.exe run`, `./wvlist.exe mkcerts`, `./wvlist.exe passwd`, etc)

It would go along with the Ergo syntax! :-)
